CREATE SCHEMA IF NOT EXISTS app;

ALTER DEFAULT PRIVILEGES FOR ROLE cl_migrate IN SCHEMA app
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO cl_rw;

ALTER DEFAULT PRIVILEGES FOR ROLE cl_migrate IN SCHEMA app
GRANT SELECT ON TABLES TO cl_ro;
