-- THIS IS ONLY TESTING BOOTSTRAP, DO NOT USE IN PRODUCTION

CREATE SCHEMA IF NOT EXISTS app;


-- API roles
CREATE ROLE cl_rw WITH NOSUPERUSER NOCREATEDB NOCREATEROLE;
CREATE ROLE cl_ro WITH NOSUPERUSER NOCREATEDB NOCREATEROLE;

GRANT USAGE ON SCHEMA app TO cl_rw;
GRANT USAGE ON SCHEMA app TO cl_ro;


-- Create database users
CREATE ROLE cl_api WITH LOGIN PASSWORD 'cl_api';
GRANT cl_rw TO cl_api;
ALTER ROLE cl_api SET search_path TO app;

CREATE ROLE cl_auth WITH LOGIN PASSWORD 'cl_auth';
ALTER ROLE cl_auth SET search_path TO auth;
