name: Deploy API server deploy script

on:
  pull_request:
    paths:
      - ".github/workflows/api-deploy-script.yml"
      - "scripts/deploy-api.sh"
  workflow_dispatch:

jobs:
  required:
    name: CI

    runs-on: ubuntu-latest

    steps:
      - run: shellcheck scripts/deploy-api.sh

  deploy-script:
    name: Deploy script

    if: github.event_name == 'workflow_dispatch'

    runs-on: github-runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Upload binary
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.API_DEPLOY_HOST }}
          username: ${{ secrets.API_DEPLOY_USER }}
          password: ${{ secrets.API_DEPLOY_PASS }}
          source: scripts/deploy-api.sh
          strip_components: 1
          target: /tmp/clearlist-api/

      - name: Install deploy script
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.API_DEPLOY_HOST }}
          username: ${{ secrets.API_DEPLOY_USER }}
          password: ${{ secrets.API_DEPLOY_PASS }}
          script: |
            sudo -n mkdir -p /opt/clearlist-api/scripts
            sudo -n install -m 755 /tmp/clearlist-api/deploy-api.sh /opt/clearlist-api/scripts/deploy.sh
