name: Deploy auth server deploy script

on:
  pull_request:
    paths:
      - ".github/workflows/auth-deploy-script.yml"
      - "scripts/deploy-auth.sh"
  workflow_dispatch:

jobs:
  required:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - run: shellcheck scripts/deploy-auth.sh

  deploy-script:
    name: Deploy script
    if: github.event_name == 'workflow_dispatch'
    needs: required
    runs-on: github-runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Upload binary
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AUTH_DEPLOY_HOST }}
          username: ${{ secrets.AUTH_DEPLOY_USER }}
          password: ${{ secrets.AUTH_DEPLOY_PASS }}
          source: scripts/deploy-auth.sh
          strip_components: 1
          target: /tmp/clearlist-auth/

      - name: Install deploy script
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.AUTH_DEPLOY_HOST }}
          username: ${{ secrets.AUTH_DEPLOY_USER }}
          password: ${{ secrets.AUTH_DEPLOY_PASS }}
          script: |
            sudo -n mkdir -p /opt/clearlist-auth/scripts
            sudo -n install -m 755 /tmp/clearlist-auth/deploy-auth.sh /opt/clearlist-auth/scripts/deploy.sh
