name: Auth CI/CD

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/auth-ci-cd.yml"
      - "apps/auth/**"
      - "package.json"
      - "pnpm-workspace.yaml"
      - "pnpm-lock.yaml"
      - "!apps/auth/**/*.md"
  pull_request:
    paths:
      - ".github/workflows/auth-ci-cd.yml"
      - "apps/auth/**"
      - "package.json"
      - "pnpm-workspace.yaml"
      - "pnpm-lock.yaml"
      - "!apps/auth/**/*.md"

permissions:
  contents: read

concurrency:
  group: auth-ci-cd-${{ github.event.pull_request.head.ref || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: CI

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: "package.json"
          cache: "pnpm"

      - name: Run install
        run: pnpm install --frozen-lockfile

      - name: Run lint
        run: pnpm auth:lint

      - name: Bootstrap and run database migration
        env:
          PGHOST: localhost
          PGDATABASE: testdb
          PGUSER: test
          PGPASSWORD: test
        run: |
          psql -v ON_ERROR_STOP=1 -f ./apps/auth/bootstrap.test.sql
          pnpm auth:migrate

      - name: Run test
        run: pnpm auth:test

  build:
    name: Build
    outputs:
      version: ${{ steps.meta.outputs.version }}
      timestamp: ${{ steps.meta.outputs.timestamp }}
      sha: ${{ steps.meta.outputs.sha }}

    needs: ci
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: package.json
          cache: pnpm

      - name: Run install
        run: pnpm install --frozen-lockfile

      - name: Build deployment
        run: pnpm auth:build

      - name: Generate metadata
        id: meta
        run: |
          version=$(pnpm --filter @clearlist/auth exec node -p "require('./package.json').version")

          echo "version=$version" >> "$GITHUB_OUTPUT"
          echo "timestamp=$(date -u +'%Y%m%d-%H%M%S')" >> "$GITHUB_OUTPUT"
          echo "sha=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      - name: Archive deployment
        run: tar -czf clearlist-auth.tar.gz -C build/auth .

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: clearlist-auth
          path: clearlist-auth.tar.gz
          retention-days: 7
          include-hidden-files: true

  deploy:
    name: CD

    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: clearlist-auth
          path: artifact/

      - name: Connect to tailscale
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci-cd

      - name: Upload deployment
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: artifact/clearlist-auth.tar.gz
          strip_components: 1
          target: /tmp/clearlist-auth/

      - name: Deploy server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            sudo -n ${{ secrets.AUTH_DEPLOY_SCRIPT }} ${{ needs.build.outputs.version }} ${{ needs.build.outputs.timestamp }} ${{ needs.build.outputs.sha }}
